CREATE TABLE BASE
(ID_BASE NUMBER PRIMARY KEY,
B_NAME VARCHAR2(10),
REGION VARCHAR2(15),
CITY VARCHAR2(15),
ADRESS VARCHAR2(20),
PHONE_NUMBER NUMBER(9));

CREATE TABLE CAR
(ID_CAR NUMBER PRIMARY KEY,
ID_BASE NUMBER, 
MARK VARCHAR2(15),
C_MODEL VARCHAR2(15),
REGISTRATION_NUMBER VARCHAR2(10),
PRODUCTION_YEAR DATE,
RENT_PRICE NUMBER(4),
C_CATEGORY VARCHAR2(10),
FOREIGN KEY (ID_BASE) REFERENCES BASE(ID_BASE));

CREATE TABLE CLIENTS
(ID_CLIENT NUMBER PRIMARY KEY,
C_NAME VARCHAR2(10),
SURNAME VARCHAR2(12),
PHONE_NUMBER NUMBER(9),
ADRESS VARCHAR2(20));

CREATE TABLE ORDERS
(ID_ORDER NUMBER PRIMARY KEY,
ID_CLIENT NUMBER,
ID_CAR NUMBER,
ORDER_DATE DATE,
RENT_START_DATE DATE,
RENT_END_DATE DATE,
FOREIGN KEY(ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT), 
FOREIGN KEY (ID_CAR) REFERENCES CAR(ID_CAR));

CREATE TABLE ORDERS_ARCHIVE
(ID_ORDER NUMBER PRIMARY KEY,
ID_CLIENT NUMBER,
ID_CAR NUMBER,
ORDER_DATE DATE,
RENT_START_DATE DATE,
RENT_END_DATE DATE,
DELETE_DATE DATE,
FOREIGN KEY(ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT), 
FOREIGN KEY (ID_CAR) REFERENCES CAR(ID_CAR));

CREATE TABLE AGENTS
(ID_AGENT NUMBER PRIMARY KEY,
ID_BASE NUMBER,
A_NAME VARCHAR2(10),
SURNAME VARCHAR2(10),
PHONE_NUMBER NUMBER(9),
SALARY NUMBER(4),
FOREIGN KEY (ID_BASE) REFERENCES BASE(ID_BASE));

CREATE TABLE MECHANICS
(ID_MECHANIC NUMBER PRIMARY KEY,
ID_BASE NUMBER,
M_NAME VARCHAR2(10),
SURNAME VARCHAR2(10),
PHONE_NUMBER NUMBER(9),
HIREDATE DATE,
SALARY NUMBER(4),
FOREIGN KEY (ID_BASE) REFERENCES BASE(ID_BASE));

CREATE TABLE REPAIRS
(ID_REPAIR NUMBER PRIMARY KEY,
ID_CAR NUMBER,
ID_MECHANIC NUMBER,
REAPAIR_DATE DATE, 
COSTS NUMBER,
FOREIGN KEY (ID_CAR) REFERENCES CAR(ID_CAR),
FOREIGN KEY (ID_MECHANIC) REFERENCES MECHANICS(ID_MECHANIC));